### ISSUE TITLE
Translation missing: `en.controllers.confirmation.permission`

### ISSUE THREAD

**Issue by ilyabogdanov** [kortirso/fantasy_sports#100]
## Background

Issue: When user signs-up and tries to navigate to Home page, she will see red error with a cryptic message. It looks like a system error to a non-sophisticated user. The error is so engaging that user may not even pay attention to what is said in content area about verifying email. She will think that web-site is broken.

https://github.com/kortirso/fantasy_sports/assets/14586414/4fc7ffbe-6be0-4e60-923f-e5c20fd62d35

## Steps to reproduce

- Sign-up
- Navigate to Home page

## Acceptance criteria

Translate whatever is not translated. Eliminate error.

**Comment by ilyabogdanov** [comment]
Hey. This is anniversary issue! Congrats myself. I'll go open a beer.

**Comment by kortirso** [comment]
fixed in https://github.com/kortirso/fantasy_sports/commit/32b6199eec6d43e61db9badd042f1eadfb20fd40
