### ISSUE TITLE
Lost unsaved data when changing language

### ISSUE THREAD

**Issue by ilyabogdanov** [kortirso/fantasy_sports#103]
## Background

I was making my team. I entered team name, and selected my favorite team. Then I decided that I want to use different language. I switched language and lost unsaved data.

Problem: using modern web applications on a daily basis, unsophisticated user will assume by default that changing language should only change text on the page. User will have all unsaved data lost.

## Acceptance criteria

Interface language is stored in database and is associated with user account.
Interface language doesn't appear in URL, and changing language doesn't cause page reload.

**Comment by kortirso** [comment]
Yes, this can be done, and user's locale can be saved to database with removing locale from url

but this is rails application, and for changing translations in rails view page must be reloaded

**Comment by ilyabogdanov** [comment]
I imagine more simple approach to solve data loss: Move language switch to a separate page e.g. settings. User will have better understanding that she needs to leave the page in order to change language. She would then save changes before leaving a page.

**Comment by kortirso** [comment]
settings page with changing locale - https://github.com/kortirso/fantasy_sports/issues/108
