### ISSUE TITLE
Impossible to make transfer when remaining points zero

### ISSUE THREAD

**Issue by ilyabogdanov** [kortirso/fantasy_sports#213]
## Background

Precondition: Initial amount of points above zero.
Problem: when making free transfer, replacing a player with someone more expensive, and if remaining amount after transfer zero, error will show up saying there is not enough money to make transfer.

<img width="853" alt="impossible_transfer_with_zero_remaining_amount" src="https://github.com/kortirso/fantasy_sports/assets/14586414/a248dca1-25d6-4d30-8b2e-2b1b0fa9ed1b">

## Acceptance criteria
It is possible to make free transfer by replacing a player with more expensive one, and with remaining balance to be zero.

**Comment by kortirso** [comment]
@ilyabogdanov what players did you want to change?

**Comment by ilyabogdanov** [comment]
> @ilyabogdanov what players did you want to change?

It was goalkeeper Johnstone -> Pope

<img width="804" alt="Screenshot 2023-11-28 at 13 15 52" src="https://github.com/kortirso/fantasy_sports/assets/14586414/3de4f3ac-f7c6-4d1e-8eb1-698b756f0cd6">

I changed another goalkeeper because of this issue. Still have Johnstone.

**Comment by kortirso** [comment]
looks like error was at initial fantasy team creation, and instead of saving budget with value 0.9, in database it was 0.899

database values are fixed, fix for initial fantasy team saving will be on production soon
