### ISSUE TITLE
"from watchlist" toggle rarely works

### ISSUE THREAD

**Issue by ilyabogdanov** [kortirso/fantasy_sports#233]
## Background

I was trying out feature "from watchlist" and I can't figure out how to make it always works. It seems to depend on screen size, but not always, sometimes opening dev console helps to make it work once or twice.

https://github.com/kortirso/fantasy_sports/assets/14586414/d356970d-81e3-407a-8acd-7d7ca2cf370b

## Acceptance criteria

Toggle works on any screen size, 10 times out of 10

**Comment by ilyabogdanov** [comment]
@kortirso how to use this feature "from watchlist"? What is it for?

**Comment by kortirso** [comment]
@ilyabogdanov you just add some players to watchlist and later you can filter such players for faster transfers
